### PR TITLE
Some Minor Suggestions

### PR DESCRIPTION
**Pull request by Frueber**
- Adding readonly access modifier to private fields set in constructors.
- For projects targeting .NET 6 and C# 10 language version, suggesting the shift to file-scoped namespaces.

### CODE REVIEW

**Comment by ktmitton** [comment]
TIL how to filter out whitespace changes in github :D

**Review by ktmitton — APPROVED** [review]

**Comment by Frueber** [comment]
> TIL how to filter out whitespace changes in github :D

😆 ... yeah, I usually try to make separate commits for that kind of thing. Seemed small enough (says the guy who didn't have to review ha).

**Comment by ktmitton** [comment]
I forced that through and turned off the code signing, that is _not_ what I meant to have as a restriction

**Comment by ktmitton** [comment]
I thought this is what code signing added:
image

**Comment by ktmitton** [comment]
I'll have to figure that out later

**Pull request merged**
